/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreeScratchRouteImport } from './routes/tree-scratch'
import { Route as SafeRouteImport } from './routes/safe'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PointsRouteImport } from './routes/points'
import { Route as LotteryRouteImport } from './routes/lottery'
import { Route as IncenseRouteImport } from './routes/incense'
import { Route as DreamRouteImport } from './routes/dream'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'

const TreeScratchRoute = TreeScratchRouteImport.update({
  id: '/tree-scratch',
  path: '/tree-scratch',
  getParentRoute: () => rootRouteImport,
} as any)
const SafeRoute = SafeRouteImport.update({
  id: '/safe',
  path: '/safe',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PointsRoute = PointsRouteImport.update({
  id: '/points',
  path: '/points',
  getParentRoute: () => rootRouteImport,
} as any)
const LotteryRoute = LotteryRouteImport.update({
  id: '/lottery',
  path: '/lottery',
  getParentRoute: () => rootRouteImport,
} as any)
const IncenseRoute = IncenseRouteImport.update({
  id: '/incense',
  path: '/incense',
  getParentRoute: () => rootRouteImport,
} as any)
const DreamRoute = DreamRouteImport.update({
  id: '/dream',
  path: '/dream',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/dream': typeof DreamRoute
  '/incense': typeof IncenseRoute
  '/lottery': typeof LotteryRoute
  '/points': typeof PointsRoute
  '/profile': typeof ProfileRoute
  '/safe': typeof SafeRoute
  '/tree-scratch': typeof TreeScratchRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/dream': typeof DreamRoute
  '/incense': typeof IncenseRoute
  '/lottery': typeof LotteryRoute
  '/points': typeof PointsRoute
  '/profile': typeof ProfileRoute
  '/safe': typeof SafeRoute
  '/tree-scratch': typeof TreeScratchRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/dream': typeof DreamRoute
  '/incense': typeof IncenseRoute
  '/lottery': typeof LotteryRoute
  '/points': typeof PointsRoute
  '/profile': typeof ProfileRoute
  '/safe': typeof SafeRoute
  '/tree-scratch': typeof TreeScratchRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/dream'
    | '/incense'
    | '/lottery'
    | '/points'
    | '/profile'
    | '/safe'
    | '/tree-scratch'
    | '/demo/tanstack-query'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/dream'
    | '/incense'
    | '/lottery'
    | '/points'
    | '/profile'
    | '/safe'
    | '/tree-scratch'
    | '/demo/tanstack-query'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/dream'
    | '/incense'
    | '/lottery'
    | '/points'
    | '/profile'
    | '/safe'
    | '/tree-scratch'
    | '/demo/tanstack-query'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  DreamRoute: typeof DreamRoute
  IncenseRoute: typeof IncenseRoute
  LotteryRoute: typeof LotteryRoute
  PointsRoute: typeof PointsRoute
  ProfileRoute: typeof ProfileRoute
  SafeRoute: typeof SafeRoute
  TreeScratchRoute: typeof TreeScratchRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tree-scratch': {
      id: '/tree-scratch'
      path: '/tree-scratch'
      fullPath: '/tree-scratch'
      preLoaderRoute: typeof TreeScratchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safe': {
      id: '/safe'
      path: '/safe'
      fullPath: '/safe'
      preLoaderRoute: typeof SafeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/points': {
      id: '/points'
      path: '/points'
      fullPath: '/points'
      preLoaderRoute: typeof PointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lottery': {
      id: '/lottery'
      path: '/lottery'
      fullPath: '/lottery'
      preLoaderRoute: typeof LotteryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incense': {
      id: '/incense'
      path: '/incense'
      fullPath: '/incense'
      preLoaderRoute: typeof IncenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dream': {
      id: '/dream'
      path: '/dream'
      fullPath: '/dream'
      preLoaderRoute: typeof DreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  DreamRoute: DreamRoute,
  IncenseRoute: IncenseRoute,
  LotteryRoute: LotteryRoute,
  PointsRoute: PointsRoute,
  ProfileRoute: ProfileRoute,
  SafeRoute: SafeRoute,
  TreeScratchRoute: TreeScratchRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
